### PR TITLE
Add UDP socket support

### PR DESCRIPTION
**Pull request by Asianadian**
Added option to UI for using UDP socket
image

Added UDP support in backend (Error message due to testing data not matching specs)
https://github.com/user-attachments/assets/8f6e7722-84bc-4908-862d-90289c1badfb

Changed variable names for inputs to distinguish between TCP and UDP

### CODE REVIEW

**Comment by linguini1** [comment]
Looks good! Two things: 

You can remove TCP support in the same PR; telemetry will be permanently sent over UDP.

What do you mean when you say the testing data isn't to spec for the error you're receiving?

**Comment by Asianadian** [comment]
The code that makes sure all packets are formatted properly is printing the error. 

I sent some text over UDP to test, since I’m not aware of any examples of proper packets for the hybrid.

Sounds good, I’ll remove the TCP.

**Comment by linguini1** [comment]
> The code that makes sure all packets are formatted properly is printing the error.
> 
> I sent some text over UDP to test, since I’m not aware of any examples of proper packets for the hybrid.

If you'd like to test with UDP packets that implement the spec, you can try running the [`hysim` pad server](https://github.com/CarletonURocketry/hysim)! You'll need
to do so on the `udp-multicast` branch though. Plain text won't be able to be decoded properly, but it does mean that
your code is properly receiving packets!

**Comment by Asianadian** [comment]
Cool! I'll give that a shot. 

Here's the UI with TCP removed:
image

**Pull request merged**
